### ISSUE TITLE
Hi, can you do this on ST3 too?

### ISSUE THREAD

**Issue by tiye** [twolfson/sublime-snippet-destroyer#2]
It's really a missing feature in ST3. Do ou get any ideas on that.

**Comment by twolfson** [comment]
Unfortunately, the ST3 behavior is significantly different from ST2. The instructions are here:

http://www.sublimetext.com/forum/viewtopic.php?f=2&t=11026

We could adjust the algorithm to always write empty snippet files. This would lead to a split finder (ST2 looks for the files via glob, ST3 looks for the files via .zip) but a common destroyer.

However, I am currently focusing on other work. As a result, I will leave this as an open issue for now.

**Comment by twolfson** [comment]
I am revisiting this as I am transitioning to Sublime Text 3 myself. The plugin doesn't require adjustments but it requires running a `.sublime-package` extractor beforehand. I will update you when everything is setup to run.

**Comment by twolfson** [comment]
Alright, everything should be good to go. For ST3, we need to extract all the files outside of their `.sublime-package` format before running the destroyer (so we can actually delete them). This is can be done via:

https://github.com/SublimeText/ExtractSublimePackage

Documentation:

https://github.com/twolfson/sublime-snippet-destroyer/tree/0.1.1#sublime-text-3-setup

**Comment by tiye** [comment]
thx
